StudentManagementSystem/Controllers/AdminClassController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentManagementSystem.Core.Contracts.Admin;
using StudentManagementSystem.Core.Models.Admin.Class;

namespace StudentManagementSystem.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminClassController : Controller
    {
        private readonly IAdminClassService adminClassService;
        private readonly IAdminTeacherService adminTeacherService;
        private readonly IAdminCourseService adminCourseService;

        public AdminClassController(
            IAdminClassService adminClassService,
            IAdminTeacherService adminTeacherService,
            IAdminCourseService adminCourseService)
        {
            this.adminClassService = adminClassService;
            this.adminTeacherService = adminTeacherService;
            this.adminCourseService = adminCourseService;
        }

        [HttpGet]
        public async Task<IActionResult> CreateClass()
        {
            var model = new ClassFormViewModel()
            {
                Teachers = await adminTeacherService.GetFreeTeachersAsync(),
                AvailableCourses = await adminCourseService.GetAllCoursesAsync()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateClass(ClassFormViewModel model)
        {
            var classes = await adminClassService.GetAllClassesAsync();

            if (classes.Any(c => c.Name == model.Name))
            {
                ModelState.AddModelError(nameof(model.Name), "Class already exists.");
            }

            if (!ModelState.IsValid)
            {
                model.Teachers = await adminTeacherService.GetFreeTeachersAsync();
                model.AvailableCourses = await adminCourseService.GetAllCoursesAsync();
                return View(model);
            }

            var id = await adminClassService.CreateClassAsync(model);
            return RedirectToAction(nameof(DetailsClass), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> AllClasses([FromQuery] AllClassesQueryModel query)
        {
            var classes = await adminClassService.AllAsync(
                query.Teacher,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                query.ClassesPerPage);

            query.Teachers = await adminTeacherService.GetAllTeachersNamesAsync();
            query.TotalClassesCount = classes.TotalClassesCount;
            query.Classes = classes.Classes;
            query.TotalPages = (int)Math.Ceiling(classes.TotalClassesCount / (double)query.ClassesPerPage);
            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> DetailsClass(int id)
        {
            if (await adminClassService.ClassExistAsync(id) == false)
            {
                return BadRequest();
            }
            var course = await adminClassService.GetClassDetailsModelByIdAsync(id);
            return View(course);
        }

        [HttpGet]
        public async Task<IActionResult> EditClass(int id)
        {
            if (await adminClassService.ClassExistAsync(id) == false)
            {
                return BadRequest();
            }
            var model = await adminClassService.GetClassFormModelByIdAsync(id);

            if (model != null)
            {
                model.Teachers = await adminTeacherService.GetFreeTeachersAsync();
                model.AvailableCourses = await adminCourseService.GetAllCoursesAsync();
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditClass(int id, ClassFormViewModel model)
        {
            if (await adminClassService.ClassExistAsync(id) == false)
            {
                return BadRequest();
            }
            if (!ModelState.IsValid)
            {
                model.Teachers = await adminTeacherService.GetFreeTeachersAsync();
                model.AvailableCourses = await adminCourseService.GetAllCoursesAsync();
                return View(model);
            }
            await adminClassService.EditClassAsync(id, model);
            return RedirectToAction(nameof(DetailsClass), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> DeleteClass(int id)
        {
            if (await adminClassService.ClassExistAsync(id) == false)
            {
                return BadRequest();
            }
            await adminClassService.DeleteClassAsync(id);
            return RedirectToAction(nameof(AllClasses));
        }
    }
}

StudentManagementSystem/Controllers/AdminCourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentManagementSystem.Core.Contracts.Admin;
using StudentManagementSystem.Core.Models.Admin.Course;
using System.Security.Claims;

namespace StudentManagementSystem.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminCourseController : Controller
    {
        private IAdminCourseService adminCourseService;
        private IAdminTeacherService adminTeacherService;

        public AdminCourseController(
            IAdminCourseService adminCourseService
            , IAdminTeacherService adminTeacherService)
        {
            this.adminCourseService = adminCourseService;
            this.adminTeacherService = adminTeacherService;
        }

        [HttpGet]
        public async Task<IActionResult> CreateCourse()
        {
            var model = new CourseFormViewModel()
            {
                Teachers = await adminTeacherService.GetAllTeachersAsync()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateCourse(CourseFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Teachers = await adminTeacherService.GetAllTeachersAsync();
                return View(model);
            }

            var publisherId = User.GetId();

            var id = await adminCourseService.CreateCourseAsync(model, publisherId);

            return RedirectToAction(nameof(DetailsCourse), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> AllCourses([FromQuery] AllCoursesQueryModel query)
        {
            var courses = await adminCourseService.AllAsync(
                query.Teacher,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                query.CoursesPerPage);

            query.Teachers = await adminTeacherService.GetAllTeachersNamesAsync();
            query.TotalCoursesCount = courses.TotalCoursesCount;
            query.Courses = courses.Courses;
            query.TotalPages = (int)Math.Ceiling(courses.TotalCoursesCount / (double)query.CoursesPerPage);
            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> DetailsCourse(int id)
        {
            if (await adminCourseService.CourseExistAsync(id) == false)
            {
                return BadRequest();
            }
            var course = await adminCourseService.GetCourseDetailsModelByIdAsync(id);
            return View(course);
        }


        [HttpGet]
        public async Task<IActionResult> EditCourse(int id)
        {
            if (await adminCourseService.CourseExistAsync(id) == false)
            {
                return BadRequest();
            }

            var model = await adminCourseService.GetCourseFormModelByIdAsync(id);

            if (model != null)
            {
                model.Teachers = await adminTeacherService.GetAllTeachersAsync();
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditCourse(int id, CourseFormViewModel model)
        {
            if (await adminCourseService.CourseExistAsync(id) == false)
            {
                return BadRequest();
            }
            if (!ModelState.IsValid)
            {
                model.Teachers = await adminTeacherService.GetAllTeachersAsync();
                return View(model);
            }

            var publisherId = User.GetId();

            await adminCourseService.EditCourseAsync(id, model, publisherId);

            return RedirectToAction(nameof(DetailsCourse), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> DeleteCourse(int id)
        {
            if (await adminCourseService.CourseExistAsync(id) == false)
            {
                return BadRequest();
            }

            await adminCourseService.DeleteCourseAsync(id);

            return RedirectToAction(nameof(AllCourses));
        }
    }
}

StudentManagementSystem/Controllers/AdminScheduleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentManagementSystem.Core.Contracts.Admin;
using StudentManagementSystem.Core.Models.Admin.Schedule;

namespace StudentManagementSystem.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminScheduleController : Controller
    {
        private readonly IAdminScheduleService scheduleService;
        private readonly IAdminCourseService adminCourseService;
        private readonly IAdminClassService adminClassService;

        public AdminScheduleController(
            IAdminScheduleService _scheduleService, 
            IAdminCourseService _adminCourseService,
            IAdminClassService _adminClassService)
        {
            scheduleService = _scheduleService;
            adminCourseService = _adminCourseService;
            adminClassService = _adminClassService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var schedules = await adminClassService.GetAllClassesAsync();
            return View(schedules);
        }

        [HttpGet]
        public async Task<IActionResult> ClassSchedule(int classId)
        {
            var model = await scheduleService.GetCourseSchedulesByIdAsync(classId);
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new CourseScheduleInputModel()
            {
                Courses = await adminCourseService.GetAllCoursesAsync(),
                Classes = await adminClassService.GetAllClassesAsync()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(CourseScheduleInputModel model)
        {
            if (ModelState.IsValid)
            {
                await scheduleService.AddCourseScheduleAsync(model);
                return RedirectToAction("Index","AdminHome");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await scheduleService.GetCourseScheduleByIdAsync(id);

            model.Courses = await adminCourseService.GetAllCoursesAsync();
            model.Classes = await adminClassService.GetAllClassesAsync();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CourseScheduleInputModel model)
        {
            if (ModelState.IsValid)
            {
                await scheduleService.EditCourseScheduleAsync(id, model);
                return RedirectToAction(nameof(ClassSchedule), new { classId = model.ClassId });
            }
            model.Courses = await adminCourseService.GetAllCoursesAsync();
            model.Classes = await adminClassService.GetAllClassesAsync();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await scheduleService.DeleteCourseScheduleAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

StudentManagementSystem/Controllers/AdminTeacherController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentManagementSystem.Core.Contracts.Admin;
using StudentManagementSystem.Core.Models.Admin.Teacher;
using static StudentManagementSystem.Core.Constants.ErrorMessageConstants;

namespace StudentManagementSystem.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminTeacherController : Controller
    {
        private readonly IAdminTeacherService adminTeacherService;
        private readonly IAdminCourseService adminCourseService;
        private readonly IAdminService adminService;

        public AdminTeacherController(
            IAdminTeacherService adminTeacherService,
            IAdminCourseService adminCourseService,
            IAdminService adminService)
        {
            this.adminTeacherService = adminTeacherService;
            this.adminCourseService = adminCourseService;
            this.adminService = adminService;
        }

        [HttpGet]
        public async Task<IActionResult> CreateTeacher()
        {
            var model = new TeacherFormViewModel()
            {
                AvailableCourses = await adminCourseService.GetAllCoursesAsync()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateTeacher(TeacherFormViewModel model, IFormFile? profilePictureFile)
        {
            if (await adminService.EmailExistAsync(model.Email) == false)
            {
                ModelState.AddModelError(nameof(model.Email), InvalidEmailMessage);
            }

            if (!ModelState.IsValid)
            {
                model.AvailableCourses = await adminCourseService.GetAllCoursesAsync();
                return View(model);
            }

            var id = await adminTeacherService.CreateTeacherAsync(model, profilePictureFile);

            return RedirectToAction(nameof(DetailsTeacher), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> AllTeachers([FromQuery] AllTeachersQueryModel query)
        {
            var teachers = await adminTeacherService.AllAsync(
                query.Course,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                query.TeachersPerPage);

            query.Courses = await adminCourseService.GetAllCoursesNamesAsync();
            query.TotalTeachersCount = teachers.TotalTeachersCount;
            query.Teachers = teachers.Teachers;
            query.TotalPages = (int)Math.Ceiling(teachers.TotalTeachersCount / (double)query.TeachersPerPage);

            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> DetailsTeacher(int id)
        {
            if (await adminTeacherService.ExistAsync(id) == false)
            {
                return BadRequest();
            }
            var student = await adminTeacherService.GetTeacherDetailsModelByIdAsync(id);
            return View(student);
        }

        [HttpGet]
        public async Task<IActionResult> EditTeacher(int id)
        {
            if (await adminTeacherService.ExistAsync(id) == false)
            {
                return BadRequest();
            }

            var model = await adminTeacherService.GetTeacherFormModelByIdAsync(id);

            if (model != null)
            {
                model.Courses = await adminCourseService.GetAllCoursesAsync();
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditTeacher(int id, TeacherFormViewModel model, IFormFile? profilePictureFile)
        {
            if (await adminTeacherService.ExistAsync(id) == false)
            {
                return BadRequest();
            }
            if (!ModelState.IsValid)
            {
                model.Courses = await adminCourseService.GetAllCoursesAsync();
                return View(model);
            }

            await adminTeacherService.EditTeacherAsync(id, model, profilePictureFile);

            return RedirectToAction(nameof(DetailsTeacher), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> DeleteTeacher(int id)
        {
            if (await adminTeacherService.ExistAsync(id) == false)
            {
                return BadRequest();
            }
            await adminTeacherService.DeleteTeacherAsync(id);
            return RedirectToAction(nameof(AllTeachers));
        }

    }
}

StudentManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @inherits Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentManagementSystem</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/favicon.ico" alt="Icon" style="width: 30px; height: 30px; margin-right: 5px; vertical-align:top" />
                    Web<span style="color: dodgerblue; font-weight: 600;">Score</span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mr-auto">
                        @if (User.IsInRole("Teacher"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Teacher" asp-action="AllClasses">Classes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Teacher" asp-action="AllNews">Add News</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Teacher" asp-action="Profile">Profile</a>
                            </li>
                        }
                        @if (User.IsInRole("Student"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Student" asp-action="AllNews">News</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Student" asp-action="AllGrades">Grades</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Student" asp-action="AllRemarks">Remarks</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Student" asp-action="AllAbsences">Absences</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Student" asp-action="Schedule">Courses Schedule</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Student" asp-action="Profile">Profile</a>
                            </li>
                        }
                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="adminDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Create
                                </a>
                                <div class="dropdown-menu" aria-labelledby="adminDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminStudent" asp-action="CreateStudent">Student</a>
                                    <div class="dropdown-divider" style="margin:0 1rem "></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminTeacher" asp-action="CreateTeacher">Teacher</a>
                                    <div class="dropdown-divider" style="margin:0 1rem "></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminCourse" asp-action="CreateCourse">Course</a>
                                    <div class="dropdown-divider" style="margin:0 1rem "></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminClass" asp-action="CreateClass">Class</a>
                                    <div class="dropdown-divider" style="margin:0 1rem "></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminSchedule" asp-action="Add">Schedule</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="adminDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Manage
                                </a>
                                <div class="dropdown-menu" aria-labelledby="adminDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminStudent" asp-action="AllStudents">Students</a>
                                    <div class="dropdown-divider" style="margin:0 1rem "></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminTeacher" asp-action="AllTeachers">Teachers</a>
                                    <div class="dropdown-divider" style="margin:0 1rem "></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminCourse" asp-action="AllCourses">Courses</a>
                                    <div class="dropdown-divider" style="margin:0 1rem "></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminClass" asp-action="AllClasses">Classes</a>
                                    <div class="dropdown-divider" style="margin:0 1rem "></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminSchedule" asp-action="Index">Schedules</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="adminDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Roles
                                </a>
                                <div class="dropdown-menu" aria-labelledby="adminDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminUserManage" asp-action="CreateRole">Create</a>
                                    <div class="dropdown-divider" style="margin:0 1rem "></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminUserManage" asp-action="EditRole">Edit</a>
                                    <div class="dropdown-divider" style="margin:0 1rem "></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminUserManage" asp-action="AddUserToRole">Add User</a>
                                    <div class="dropdown-divider" style="margin:0 1rem "></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminUserManage" asp-action="RemoveUserFromRole">Remove User</a>
                                </div>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; @DateTime.Today.Year - StudentManagementSystem
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    @* <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script> *@
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>